/*

(c) 2016 Copyright Vaclav2016 https://github.com/vaclav2016, jabber id vaclav2016@jabber.cz

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strophe.h>
#include <error.h>
#include <errno.h>
#include <pthread.h>
#include <unistd.h>
#include <hiredis/hiredis.h>
#include "ini.h"
#include "logger.h"

#define MESSAGE_BUF_SIZE 1024*64
#define MAX_INCOME_MESSAGE_SIZE 4*1024

#define SKIP_SPACE(a) while(*a == ' ' && *a!=0) { a++;}
#define DEFAUL_STR_SIZE 1024

const char *PublishCmd = "PUBLISH %s %s";
const char *SubscribeCmdTemplate = "SUBSCRIBE %s";
const char *Prefix = "jid:";
const int PrefixLen = 4;

struct MessageQueue {
	char *body;
	struct MessageQueue *next;
};

typedef struct XmppRedisContext {
	char redisHost[DEFAUL_STR_SIZE];
	uint64_t redisPort;
	char online;
	struct timeval redisTimeout;
	char jid[DEFAUL_STR_SIZE];
	char pwd[DEFAUL_STR_SIZE];
	char inboundQueue[DEFAUL_STR_SIZE];
	char outboundQueue[DEFAUL_STR_SIZE];
	char subscribeCmd[DEFAUL_STR_SIZE];
	xmpp_ctx_t *ctx;
	xmpp_conn_t *conn;
	pthread_mutex_t fromRedisQueueLock;
	struct MessageQueue *fromRedisQueue;
	struct MessageQueue *sendToXmppQueue;
	struct MessageQueue *sendToRedisQueue;
} *XMPP_REDIS_CONTEXT;

int version_handler(xmpp_conn_t * const conn, xmpp_stanza_t * const stanza, void * const userdata) {
	xmpp_stanza_t *reply, *query, *name, *version, *text;
	const char *ns;
	XMPP_REDIS_CONTEXT conf = userdata;
	xmpp_ctx_t *ctx = conf->ctx;

	reply = xmpp_stanza_reply(stanza);
	xmpp_stanza_set_type(reply, "result");

	query = xmpp_stanza_new(ctx);
	xmpp_stanza_set_name(query, "query");
	ns = xmpp_stanza_get_ns(xmpp_stanza_get_children(stanza));
	if (ns) {
		xmpp_stanza_set_ns(query, ns);
	}

	name = xmpp_stanza_new(ctx);
	xmpp_stanza_set_name(name, "name");
	xmpp_stanza_add_child(query, name);
	
	text = xmpp_stanza_new(ctx);
	xmpp_stanza_set_text(text, "anonymous bot");
	xmpp_stanza_add_child(name, text);
	
	version = xmpp_stanza_new(ctx);
	xmpp_stanza_set_name(version, "version");
	xmpp_stanza_add_child(query, version);
	
	text = xmpp_stanza_new(ctx);
	xmpp_stanza_set_text(text, "1.0");
	xmpp_stanza_add_child(version, text);
	
	xmpp_stanza_add_child(reply, query);

	xmpp_send(conn, reply);
	xmpp_stanza_release(reply);
	return 1;
}


int message_handler(xmpp_conn_t * const conn, xmpp_stanza_t * const stanza, void * const userdata) {
	xmpp_stanza_t *reply, *body, *text;
	char *intext, *replytext;
	XMPP_REDIS_CONTEXT conf = userdata;
	xmpp_ctx_t *ctx = conf->ctx;

	if(!xmpp_stanza_get_child_by_name(stanza, "body")) {
		return 1;
	}
	if(xmpp_stanza_get_type(stanza) !=NULL && !strcmp(xmpp_stanza_get_type(stanza), "error")) {
		return 1;
	}

	intext = xmpp_stanza_get_text(xmpp_stanza_get_child_by_name(stanza, "body"));
	const char *from = xmpp_stanza_get_from(stanza);

	if( strlen(intext) > MAX_INCOME_MESSAGE_SIZE) {
		reply = xmpp_stanza_reply(stanza);
		xmpp_message_set_body(reply, "[DROP] Your message is too big and has been droped.");
		xmpp_send(conn, reply);
		xmpp_stanza_release(reply);
		free(replytext);
		return 1;
	}

	replytext = (char *) malloc(strlen(from) + strlen(intext) + 2 + PrefixLen);
	strcpy(replytext, Prefix);
	strcat(replytext, from);
	char *stop = strchr(replytext, '/');
	if( stop != NULL ) {
		*stop = 0;
	}

	char log[1024];
	snprintf(log, sizeof(log), "Receive message from %s", replytext);
	logger(LOG_INFO, log);

	strcat(replytext, "\n");
	strcat(replytext, intext);
	xmpp_free(ctx, intext);
	char *t = replytext;

	while(*t) {
		if(*t=='"') {
			*t = ' ';
		}
		t++;
	}

	struct MessageQueue *nm = malloc(sizeof(struct MessageQueue));
	nm->body = malloc(strlen(replytext)+1);
	strcpy(nm->body, replytext);
	nm->next = conf->sendToRedisQueue;
	conf->sendToRedisQueue = nm;

	free(replytext);
	return 1;
}

/* define a handler for connection events */
void conn_handler(xmpp_conn_t * const conn, const xmpp_conn_event_t status, 
		  const int error, xmpp_stream_error_t * const stream_error,
		  void * const userdata) {
	XMPP_REDIS_CONTEXT conf = userdata;
	xmpp_ctx_t *ctx = conf->ctx;

	if (status == XMPP_CONN_CONNECT) {
		xmpp_stanza_t* pres;

		char log[1024];
		snprintf(log, sizeof(log), "Connected to jabber server for %s", conf->jid);
		logger(LOG_INFO, log);

		xmpp_handler_add(conn,version_handler, "jabber:iq:version", "iq", NULL, conf);
		xmpp_handler_add(conn,message_handler, NULL, "message", NULL, conf);

		pres = xmpp_stanza_new(ctx);
		xmpp_stanza_set_name(pres, "presence");
		xmpp_send(conn, pres);
		xmpp_stanza_release(pres);
		conf->online = 1;
	} else if (status == XMPP_CONN_DISCONNECT || status == XMPP_CONN_FAIL){
		char log[1024];
		snprintf(log, sizeof(log), "Disconnect from jabber server for %s", conf->jid);
		logger(LOG_INFO, log);
		conf->online = 0;
	}
}

redisContext *connectRedis(XMPP_REDIS_CONTEXT conf, redisContext *rc) {
	if (rc == NULL || rc->err) {
		logger(LOG_INFO, "Reconnect to REDIS-server");
		if (rc) {
			redisFree(rc);
		}
		rc = redisConnectWithTimeout(conf->redisHost, conf->redisPort, conf->redisTimeout);
		if (rc != NULL && !rc->err) {
			logger(LOG_INFO, "Connected to REDIS-server");
		}
	}
	return rc;
}

void sendMessage(xmpp_ctx_t *ctx, xmpp_conn_t *conn, char *messageSource) {
	char *toJid = messageSource;
	char *messageBody = strchr(messageSource, '\n');

	if( messageBody == NULL ) {
		return;
	}
	*messageBody = 0;
	messageBody++;

	if(strchr(toJid, '@') != NULL && strchr(toJid, '.') != NULL && strncmp(Prefix, toJid, PrefixLen) == 0 ) {
		char log[1024];
		snprintf(log, sizeof(log), "Send message to %s", toJid);
		logger(LOG_INFO, log);

		toJid += PrefixLen;
	} else {
		return;
	}

	SKIP_SPACE(messageBody);
	SKIP_SPACE(toJid);

	xmpp_stanza_t *newMsg = xmpp_message_new(ctx, "chat", toJid, NULL /* id */);
	xmpp_message_set_body(newMsg, messageBody);
	xmpp_send(conn, newMsg);
	xmpp_stanza_release(newMsg);
}

void *redisClientThread(void *args) {
	XMPP_REDIS_CONTEXT conf = args;
	redisContext *rSubscCtx = connectRedis(conf, NULL);
	while(1) {
		rSubscCtx = connectRedis(conf, rSubscCtx);
		redisReply *reply = redisCommand(rSubscCtx, conf->subscribeCmd);
		freeReplyObject(reply);
		while(redisGetReply(rSubscCtx, (void**)&reply) == REDIS_OK) {
			if (reply->type == REDIS_REPLY_ARRAY) {
				pthread_mutex_lock(&conf->fromRedisQueueLock);
				int i;
				for (i = 0; i < reply->elements; i++) {
					if(reply->element[i]->type == REDIS_REPLY_STRING) {
						struct MessageQueue *msg = malloc(sizeof(struct MessageQueue));
						msg->body = malloc(strlen(reply->element[i]->str) + 1);
						strcpy(msg->body, reply->element[i]->str);
						msg->next = conf->fromRedisQueue;
						conf->fromRedisQueue = msg;
					}
				}
				pthread_mutex_unlock(&conf->fromRedisQueueLock);
			}
			freeReplyObject(reply);
		}
	}
	redisFree(rSubscCtx);
	return NULL;
}

int readConfig(void *config, XMPP_REDIS_CONTEXT conf, char *botSectionName) {
	char redisSectionName[256];

	if (config == NULL) {
		logger(LOG_ERROR, "ini_load fail");
		return 1;
	}

	ini_getstr(config, botSectionName, "redis", redisSectionName, sizeof(redisSectionName));
	ini_getstr(config, botSectionName, "jid", conf->jid, DEFAUL_STR_SIZE);
	ini_getstr(config, botSectionName, "password", conf->pwd, DEFAUL_STR_SIZE);

	ini_getstr(config, redisSectionName, "host", conf->redisHost, DEFAUL_STR_SIZE);
	ini_getint(config, redisSectionName, "port", &conf->redisPort);

	ini_getstr(config, botSectionName, "inbound", conf->inboundQueue, DEFAUL_STR_SIZE);
	ini_getstr(config, botSectionName, "outbound", conf->outboundQueue, DEFAUL_STR_SIZE);

	return 0;

}

void sendMessages_once(XMPP_REDIS_CONTEXT xrCtx) {
	struct MessageQueue *this;
	while ( (this = xrCtx->sendToXmppQueue) != NULL) {
		xrCtx->sendToXmppQueue = xrCtx->sendToXmppQueue->next;
		sendMessage(xrCtx->ctx, xrCtx->conn, this->body);
		free(this->body);
		free(this);
	}
}

void populateMessagesFromRedis(XMPP_REDIS_CONTEXT xrCtx) {
	struct MessageQueue *this;
	pthread_mutex_lock(&xrCtx->fromRedisQueueLock);
	while( (this = xrCtx->fromRedisQueue) != NULL ) {
		xrCtx->fromRedisQueue = xrCtx->fromRedisQueue->next;
		this->next = xrCtx->sendToXmppQueue;
		xrCtx->sendToXmppQueue = this;
	}
	pthread_mutex_unlock(&xrCtx->fromRedisQueueLock);
}

void populateMesageToRedis(XMPP_REDIS_CONTEXT xrCtx) {
	if( xrCtx->sendToRedisQueue == NULL ) {
		return;
	}
	redisContext *rc = redisConnectWithTimeout(xrCtx->redisHost, xrCtx->redisPort, xrCtx->redisTimeout);
	if (rc != NULL && !rc->err) {
		struct MessageQueue *this;
		while( (this = xrCtx->sendToRedisQueue) != NULL) {
			xrCtx->sendToRedisQueue = xrCtx->sendToRedisQueue->next;
			int bufLen = strlen(PublishCmd) + strlen(this->body) + strlen(xrCtx->inboundQueue);
			char *buf = malloc(bufLen);
			snprintf(buf, bufLen, PublishCmd, xrCtx->inboundQueue, this->body);
			freeReplyObject(redisCommand(rc, buf));
			free(buf);
			free(this->body);
			free(this);
		}
		redisFree(rc);
	}
}

int validateConfig(XMPP_REDIS_CONTEXT xrCtx) {
	if(strlen(xrCtx->jid)==0) {
		logger(LOG_ERROR, "Invalid config. Empty xmpp/jid");
		return 1;
	}
	if(strlen(xrCtx->pwd)==0) {
		logger(LOG_ERROR, "Invalid config. Empty xmpp/pass");
		return 1;
	}
	if(strlen(xrCtx->redisHost)==0) {
		logger(LOG_ERROR, "Invalid config. Empty redis/host");
		return 1;
	}
	if(xrCtx->redisPort == 0) {
		logger(LOG_ERROR, "Invalid config. Empty redis/port");
		return 1;
	}
	if(strlen(xrCtx->inboundQueue)==0) {
		logger(LOG_ERROR, "Invalid config. Empty queue/inbound");
		return 1;
	}
	if(strlen(xrCtx->outboundQueue)==0) {
		logger(LOG_ERROR, "Invalid config. Empty queue/outbound");
		return 1;
	}
	return 0;
}

void startBot(char *name, void *cfg) {
	XMPP_REDIS_CONTEXT xrCtx = malloc(sizeof(struct XmppRedisContext));
	xrCtx->redisTimeout.tv_sec = 10;
	xrCtx->redisTimeout.tv_usec = 500000;
	xrCtx->fromRedisQueue = NULL;
	xrCtx->sendToXmppQueue = NULL;
	xrCtx->sendToRedisQueue = NULL;
	xrCtx->online = 0;
	xrCtx->conn = NULL;
	pthread_mutex_init(&xrCtx->fromRedisQueueLock, NULL);

	if(readConfig(cfg, xrCtx, name)) {
		logger(LOG_ERROR, "Could not read config");
		return;
	}
	if(validateConfig(xrCtx)) {
		logger(LOG_ERROR, "Bad config");
		return;
	}
	snprintf(xrCtx->subscribeCmd, DEFAUL_STR_SIZE, SubscribeCmdTemplate, xrCtx->outboundQueue);

//	log = xmpp_get_default_logger(XMPP_LEVEL_DEBUG); /* pass NULL instead to silence output */
	xmpp_get_default_logger((xmpp_log_level_t)NULL);
//	ctx = xmpp_ctx_new(NULL, log);
	xrCtx->ctx = xmpp_ctx_new(NULL, NULL);

	pthread_t thread;
	pthread_create(&thread, NULL, redisClientThread, xrCtx);

	while(1) {
		if(xrCtx->online) {
			xmpp_run_once(xrCtx->ctx, 10*1000);
			populateMesageToRedis(xrCtx);
			populateMessagesFromRedis(xrCtx);
			sendMessages_once(xrCtx);
		} else {
			if(xrCtx->conn!=NULL) {
				xmpp_conn_release(xrCtx->conn);
				xrCtx->conn = NULL;
			}
			xrCtx->conn = xmpp_conn_new(xrCtx->ctx);
			xmpp_conn_set_keepalive(xrCtx->conn, 60000, 30000);

			xmpp_conn_set_jid(xrCtx->conn, xrCtx->jid);
			xmpp_conn_set_pass(xrCtx->conn, xrCtx->pwd);

			xmpp_connect_client(xrCtx->conn, NULL, 0, conn_handler, xrCtx);

			while(!xrCtx->online) {
				xmpp_run_once(xrCtx->ctx, 3*60*1000);
			}
		}
	}

	logger(LOG_INFO, "Shutdown");
	if(xrCtx->conn!=NULL) {
		xmpp_conn_release(xrCtx->conn);
		xrCtx->conn = NULL;
	}
	xmpp_ctx_free(xrCtx->ctx);

	pthread_mutex_destroy(&xrCtx->fromRedisQueueLock);
	free(xrCtx);
}

int main(int argc, char **argv) {
	if(argc != 3) {
		error(1, errno, "Usage: xmppredis section config_file\n");
	}

	pid_t pid = fork();
	if (pid < 0) {
		exit(EXIT_FAILURE);
	}
	if (pid > 0) {
		printf("%d", pid);
		exit(EXIT_SUCCESS);
	}
	umask(0);
	close(STDIN_FILENO);
	close(STDOUT_FILENO);
	close(STDERR_FILENO);

	xmpp_initialize();

	void *config = ini_load(argv[2]);

	char logFileName[1024];
	ini_getstr(config, "", "log", logFileName, sizeof(logFileName));
	logger_init(logFileName);


	startBot(argv[1], config);
	ini_free(config);
	xmpp_shutdown();
	logger_destroy();
	return 0;
}
