/*
(с) 2016 Copyright by vaclav2016, https://github.com/vaclav2016/xmppredis/

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef _VK_H_
#define _VK_H_

#include<cjson/json.h>

#define DEFAUL_STR_SIZE 1024

typedef struct Config {
	char redisHost[DEFAUL_STR_SIZE];
	uint32_t redisPort;
	struct timeval redisTimeout;

	char app_id[DEFAUL_STR_SIZE];
	char secure_key[DEFAUL_STR_SIZE];
	char vk_id[DEFAUL_STR_SIZE];
	char pwd[DEFAUL_STR_SIZE];

	char access_token[DEFAUL_STR_SIZE];
	char need_access_token;

	char lastMessageId[DEFAUL_STR_SIZE];

	char inboundQueue[DEFAUL_STR_SIZE];
	char outboundQueue[DEFAUL_STR_SIZE];
} *CONFIG;

extern char *vk_auth(CONFIG c);
extern json_value* vk_getMessages(CONFIG c);


#endif