/*
(с) 2016 Copyright by vaclav2016, https://github.com/vaclav2016/xmppredis/

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <error.h>
#include <errno.h>
#include <pthread.h>
#include <hiredis/hiredis.h>
#include <ini/ini.h>
#include "curl-client.h"
#include "vk.h"

#define MESSAGE_BUF_SIZE 1024*64
#define SKIP_SPACE(a) while(*a == ' ' && *a!=0) { a++;}

struct Config conf;

void checkMessages(CONFIG c) {
	json_value* value = vk_getMessages(c);
	if(value != NULL) {
		json_value_free(value);
	}
}

void readConfig(char *fname, char *botSectionName) {
	char redisSectionName[1024];

	ini_t *config = ini_load(fname);

	if (config == NULL) {
		error(1, errno, "ini_load fail");
	}

	ini_read_strn(config, botSectionName, "redis", redisSectionName, sizeof(redisSectionName), NULL);

	ini_read_strn(config, botSectionName, "app_id", conf.app_id, DEFAUL_STR_SIZE, NULL);
	ini_read_strn(config, botSectionName, "secure_key", conf.secure_key, DEFAUL_STR_SIZE, NULL);

	ini_read_strn(config, botSectionName, "vk_id", conf.vk_id, DEFAUL_STR_SIZE, NULL);
	ini_read_strn(config, botSectionName, "password", conf.pwd, DEFAUL_STR_SIZE, NULL);

	ini_read_strn(config, redisSectionName, "host", conf.redisHost, DEFAUL_STR_SIZE, NULL);
	ini_read_uint32(config, redisSectionName, "port", &conf.redisPort, 0);

	ini_read_strn(config, botSectionName, "inbound", conf.inboundQueue, DEFAUL_STR_SIZE, NULL);
	ini_read_strn(config, botSectionName, "outbound", conf.outboundQueue, DEFAUL_STR_SIZE, NULL);

	ini_free(config);
}

void validateConfig() {
	if(strlen(conf.app_id)==0) {
		error(1, errno, "\033[31mInvalid config. Empty vk/app_id\033[37m\n");
	}
	if(strlen(conf.secure_key)==0) {
		error(1, errno, "\033[31mInvalid config. Empty vk/secure_key\033[37m\n");
	}
	if(strlen(conf.vk_id)==0) {
		error(1, errno, "\033[31mInvalid config. Empty vk/vk_id\033[37m\n");
	}
	if(strlen(conf.pwd)==0) {
		error(1, errno, "\033[31mInvalid config. Empty vk/password\033[37m\n");
	}
	if(strlen(conf.redisHost)==0) {
		error(1, errno, "\033[31mInvalid config. Empty redis/host\033[37m\n");
	}
	if(conf.redisPort == 0) {
		error(1, errno, "\033[31mInvalid config. Empty redis/port\033[37m\n");
	}
	if(strlen(conf.inboundQueue)==0) {
		error(1, errno, "\033[31mInvalid config. Empty queue/inbound\033[37m\n");
	}
	if(strlen(conf.outboundQueue)==0) {
		error(1, errno, "\033[31mInvalid config. Empty queue/outbound\033[37m\n");
	}
}


int main(int argc, char **argv) {
	printf("\033[34m\r");
	printf("oooooo     oooo oooo        ooooooooo.                   .o8   o8o           \n");
	printf(" `888.     .8'  `888        `888   `Y88.                \"888   `\"'           \n");
	printf("  `888.   .8'    888  oooo   888   .d88'  .ooooo.   .oooo888  oooo   .oooo.o \n");
	printf("   `888. .8'     888 .8P'    888ooo88P'  d88' `88b d88' `888  `888  d88(  \"8 \n");
	printf("    `888.8'      888888.     888`88b.    888ooo888 888   888   888  `\"Y88b.  \n");
	printf("     `888'       888 `88b.   888  `88b.  888    .o 888   888   888  o.  )88b \n");
	printf("      `8'       o888o o888o o888o  o888o `Y8bod8P' `Y8bod88P\" o888o 8""888P' ");
	printf("\033[37m\n");
	printf("(с) 2016 Copyright by \033[36mvaclav2016\033[37m, https://github.com/vaclav2016/xmppredis/\n");
	printf("\033[31mBoost License, Version 1.0, http://www.boost.org/LICENSE_1_0.txt\033[37m\n");

	if(argc != 3) {
		error(1, errno, "\033[31mUsage: vkredis section config_file\033[37m\n");
	}

	readConfig(argv[2], argv[1]);
	validateConfig();

	conf.need_access_token = 1;
	conf.lastMessageId[0] = 0;

	while(1) {
		if(conf.need_access_token) {
			vk_auth(&conf);
		} else {
			checkMessages(&conf);
		}
		sleep(30);
	}
}
